import Provider from '@/components/Provider'
import './globals.css'
import { Inter } from 'next/font/google'
import RecoilProvider from '@/components/RecoilProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Twitter-2.0',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Provider>
      <RecoilProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </RecoilProvider>
    </Provider>
  )
}
